name: CI scrape Google scholar articles

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2

    - name: Cache R packages
      uses: actions/cache@v1
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

    - name: Install system dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev
    - name: Install R package dependencies
      run: |
        if (!require('remotes')) install.packages('remotes')
        if (!require('rvest')) install.packages('rvest')
        if (!require('janitor')) install.packages('janitor')
      shell: Rscript {0}

    - name: Fetch stats and update README.md
      run: |
        Rscript scrape-google-citations.R
    - name: Commit files # Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git diff-index --quiet HEAD || (git commit -m "update data" && git push)
        
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.
